sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.5
matrix:
    fast_finish: true
    allow_failures:
        - php: 7.1
before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
before_script:
  - git clone --branch=master --depth=1 --quiet git://github.com/WoltLab/WCF.git WCF
script:
  - find files -type f -name '*.php' |xargs -I file php -l file
  - find files_wcf -type f -name '*.php' |xargs -I file php -l file
  - phpcs -p --extensions=php --standard="`pwd`/WCF/CodeSniff/WCF" files
  - phpcs -p --extensions=php --standard="`pwd`/WCF/CodeSniff/WCF" files_wcf
